version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #   - "8080:8080"
  #   links:
  #   - neo4j
  #   depends_on:
  #   - neo4j
  neo4j:
    image: neo4j:3.0
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs
    - $HOME/neo4j/conf:/conf